environment:
  EAFILE: src/EA31337.mq4
init:
- ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- appveyor DownloadFile https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.30.03/AutoHotkey_1.1.30.03_setup.exe
- appveyor DownloadFile https://web.archive.org/web/20160112133258if_/https://download.mql5.com/cdn/web/metaquotes.software.corp/mt4/mt4setup.exe?utm_campaign=www.metatrader4.com
- ps: set MT_VERSION (Get-Item 'mt4setup.exe').VersionInfo.FileVersion
- ps: echo MetaTrader version is $MT_VERSION
#- appveyor DownloadFile https://download.sysinternals.com/files/Sigcheck.zip
#- 7z x Sigcheck.zip
- AutoHotkey_1.1.30.03_setup.exe /S
- set "REPODIR=%cd%"
- ps: type scripts\ahk\install_mt4.ahk
- ps: C:\Progra~1\AutoHotkey\AutoHotkey.exe /ErrorStdOut scripts\ahk\install_mt4.ahk 2>&1 | more
- dir "C:\Program Files (x86)"
- Reg export "HKCU\Software\MetaQuotes Software\MetaTrader 4" "C:\Program Files (x86)\MetaTrader 4\registry.reg"
- 7z a metatrader4.zip "C:\Program Files (x86)\MetaTrader 4"
- dir *.zip
#- ps: scoop install ruby python
#- ps: scoop install shellcheck
before_test:
#- git submodule update --init
#- shellcheck --version
#- echo ^#define %MODE% >> src/include/EA31337/ea-mode.mqh
test_script:
#- ps: Get-ChildItem -File scripts | Foreach {shellcheck $_.fullname}
#- dir "C:\Program Files\MetaTrader"
build: off
platform: x86
