environment:
  EAFILE: src/EA31337.mq4
  access_token:
    secure: NvSSlnVYkVLxRlzrVct6rWPbW4g9h2NS0O1nc5t+FTHt7c7UI6IyLOj/z2bVzfZ7init
init:
- ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- appveyor DownloadFile https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.30.03/AutoHotkey_1.1.30.03_setup.exe
- ps: wget "https://web.archive.org/web/20160112133258if_/https://download.mql5.com/cdn/web/metaquotes.software.corp/mt4/mt4setup.exe?utm_campaign=www.metatrader4.com" -OutFile mt4setup.exe
- ps: set MT_SETUP_VERSION (Get-Item 'mt4setup.exe').VersionInfo.FileVersion
- ps: echo "MetaTrader setup version is $MT_SETUP_VERSION"
#- appveyor DownloadFile https://download.sysinternals.com/files/Sigcheck.zip
#- 7z x Sigcheck.zip
- AutoHotkey_1.1.30.03_setup.exe /S
- set "REPODIR=%cd%"
- ps: type scripts\ahk\install_mt4.ahk
- ps: C:\Progra~1\AutoHotkey\AutoHotkey.exe /ErrorStdOut scripts\ahk\install_mt4.ahk 2>&1 | more
- dir "C:\Program Files (x86)"
- ps: set MT_VERSION (Get-Item 'C:\Program Files (x86)\MetaTrader 4\terminal.exe').VersionInfo.FileVersion
- ps: echo "MetaTrader terminal version is $MT_VERSION"
- Reg export "HKCU\Software\MetaQuotes Software\MetaTrader 4" "C:\Program Files (x86)\MetaTrader 4\registry.reg"
- ps: set MT_ZIP mt-${MT_VERSION}.zip
- ps: 7z a ${MT_ZIP} "C:\Program Files (x86)\MetaTrader 4"
- dir *.zip
- mkdir releases
- mkdir releases\download
- ps: mv ${MT_ZIP} releases\download
- ps: git config --global credential.helper store
- ps: git config --global user.email "appveyor@example.com"
- ps: git config --global user.name "Appveyor"
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- ps: git tag ${MT_VERSION}
- ps: git add releases\download\*
- ps: git commit -m "Uploaded new version of MetaTrader - v${MT_VERSION}" releases\download\*
- ps: git push origin HEAD --tags

#- ps: scoop install ruby python
#- ps: scoop install shellcheck
before_test:
#- git submodule update --init
#- shellcheck --version
#- echo ^#define %MODE% >> src/include/EA31337/ea-mode.mqh
test_script:
#- ps: Get-ChildItem -File scripts | Foreach {shellcheck $_.fullname}
#- dir "C:\Program Files\MetaTrader"
build: off
platform: x86
